server:
  port: 8080

spring:

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
      - id: authservice
        uri: lb://AUTHSERVICE
        predicates:
        - Path=/api/auth/**
        filters:
        - AuthenticationFilter
      - id: agentserver
        uri: lb://AGENTSERVER
        predicates:
        - Path=/api/agent/**
        filters:
        - AuthenticationFilter
  application:
    name: gateway_server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka